version: '3.9'

services:
  timeseries-lapig:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8012:8012"
    environment:
      LAPIG_DB__uri: "postgresql://postgres:postgres@db:5432/${LAPIG_DB:-timeseries-lapig}"
      LAPIG_DB__connect_args: "{}"
      LAPIG_MONGODB_URL: "mongodb://mongodb:27017"
    volumes:
      - ../..:/APP/
    stdin_open: true
    tty: true