version: '3.9'

services:
  timeseries-lapig:
    build: .
    hostname: timeseries-lapig-dev
    container_name: timeseries-lapig-dev
    privileged: true
    ports:
      - "8012:8012"
    environment:
      LAPIG_DB__uri: "postgresql://postgres:postgres@db:5432/${LAPIG_DB:-timeseries-lapig}"
      LAPIG_DB__connect_args: "{}"
      LAPIG_MONGODB_URL: "mongodb://mongodb:27017"
    restart: always
    stdin_open: true
    tty: true
 #   volumes:
 #     - ../..:/APP/timeseries