[default]
HTTPS = false
BRANCH='dev'
APP_NAME='Timeseries Indexes'
API_NAME='dev-timeseries-indexes'
APP_DEBUG=true
TOKEN='LAPIG'

PORT=8012
HOST='127.0.0.1'

MONGODB_URL = 'localhost:27017'
MONGO_DB='timeseries'

SERVER_URL='http://localhost:3000'
#PRIVATE_KEY_FILE='/app/.service-accounts/gee.json'
LOG_CONFIG=''

ORIGINS=[
    "http://localhost:3000",
    "http://localhost:4200",
]

[default.db]
uri = ""
connect_args = {check_same_thread=false}
echo = false


[main]
HTTPS = true
PORT=3000
HOST='0.0.0.0'

[develop]
HTTPS = true
PORT=3000
HOST='0.0.0.0'
#PRIVATE_KEY_FILE='/home/tharles/Downloads/GEE/blissful-axiom-314717-845a6f8c6805.json'


